### ISSUE TITLE
Erreur de redirection SSL de http://www.aides-territoires.beta.gouv.fr/

### ISSUE THREAD

**Issue by jdauphant** [MTES-MCT/aides-territoires#138]
![image](https://user-images.githubusercontent.com/1238254/89202925-013fa800-d5b4-11ea-9647-73941081eb11.png)

http://www.aides-territoires.beta.gouv.fr/ redirige vers https://www.aides-territoires.beta.gouv.fr/ mais le certificat SSL de https://www.aides-territoires.beta.gouv.fr/ 
 n'est pas valide.

**Comment by Ash-Crow** [comment]
Il semble que le problème soit réglé. N'hésitez pas à réouvrir si besoin.
