### ISSUE TITLE
Accès à un dump récent de la base de données ?

### ISSUE THREAD

**Issue by samuelpath** [MTES-MCT/aides-territoires#140]
La page de "onboarding" indique :

```
Il sera nécessaire de mettre à jour la base de donnée à partir d'un dump récent.
```

Où et comment se procurer ce dump ?

Vu que le projet est open-source, serait-il possible de mettre à disposition un dump récent en permanence pour toute personne souhaitant contribuer ?

**Comment by thibault** [comment]
@samuelpath Bonjour Samuel. Le code du projet est open-source mais les données ne le sont pas.

Il serait en effet très malvenu de notre part de laisser en accès libre les données à caractères personnel (emails téléphones, noms, etc.) de tous les utilisateurs inscrits sur la plateforme. Ce serait d'ailleurs parfaitement illégal et nous exposerait à de lourdes sanctions.

Seules les données des aides sont librement récupérables, via notre api.

Récupérer un dump nécessite d'être titulaire d'un contrat de mission en bonne et due forme auprès de la dinum.

Concernant tes nombreux autres tickets, j'ai vu que tu avais à cœur de m'éviter de m'ennuyer pour ma rentrée :) J'y jetterai un œil au cours des prochains jours.

**Comment by samuelpath** [comment]
@thibault Merci pour ton retour Thibault.
Après réflexion, ta réponse à ma question est tellement évidente que j'ai presque honte de l'avoir posée ^^.
Concernant les autres tickets, c'est juste des détails mineurs que j'ai vus en essayant de prendre en main le site, donc absolument rien de pressant ;).
