### ISSUE TITLE
Espaces en trop avant virgules et points sur /plateforme-aides-territoires et /porteurs-aides

### ISSUE THREAD

**Issue by samuelpath** [MTES-MCT/aides-territoires#142]
Sur la page statique `/plateforme-aides-territoires/`, je vois : 

> gagner du temps aux acteurs locaux , de contribuer…

>  de toutes les collectivités aux informations sur les aides , est…

> au sein de la Fabrique numérique, l'incubateur des Ministères de la Transition Ecologique et Solidaire  et de la Cohésion des Territoires et des Relations avec les Collectivités Territoriales .

> Aides-territoires est une startup d'État du réseau beta.gouv .

Sur la page statique `/porteurs-aides/`, je vois : 

> Grâce à Aides-territoires , les…

Il y a dans les 5 cas un espace en trop avant une virgule ou un point.

De ce que je comprends, les 3 pages `/plateforme-aides-territoires`, `/porteurs-aides/` et `/aides-collectivités/` sont des pages qui sont servies de manière statiques et dont le code source n'est pas dans le dépôt Django. Vous confirmez ? Et du coup où sont hébergées ces pages ? Elles n'ont pas été "open-sourcées" ?

**Comment by Ash-Crow** [comment]
Merci pour le signalement, c'est maintenant corrigé.

Ce ne sont pas des pages statiques mais des pages dynamiques faites avec un éditeur WYSIWYG côté admin.
