### ISSUE TITLE
API aides territoires

### ISSUE THREAD

**Issue by oceatoon** [MTES-MCT/aides-territoires#15]
Bonjour 
est ce qu'il y a une api pour interopérer avec aides-territoires ?
on aimerait le connecter dans le contexte du contrat de transition ecologique 
merci

**Comment by thibault** [comment]
Bonjour @oceatoon,

Merci de votre intérêt pour Aides-territoires.

Nous avons récemment travaillé au développement d'une api permettant de récupérer les aides présentes sur Aides-territoires. Toutefois, il s'agit d'un développement très récent qui n'est pas encore passé en production. Vous n'aurez pas longtemps à attendre, ceci dit, puisque ladite mise en production est prévue pour ce soir.

Vous pouvez avoir un [aperçu de l'API sur notre serveur de recette](https://aides-territoires.jouannic.fr/data/). J'attire votre attention sur le fait que cette url est utilisée à des fins de tests privés, ne contient pas de données à jour, et est donnée à titre purement indicatif.

Pour l'instant, l'api ne concerne que les données des aides en lecture seule. Toutefois, nous sommes intéressés par tout retour aussi, si vos besoins diffèrent, n'hésitez pas à nous en parler.

Cordialement.

**Comment by oceatoon** [comment]
genial merci , quelle synchronicité !!
merci pour le retour rapide
on va réutilisé le contenu sur communecter.org dans le déploiement des CTE
(contrat de transition écologie)
et l'associer au dépot de projet , permettant d’accélérer et faciliter
l’accès aux aides dans la section financement
c'est un usage directe , interopérant d'aides-territoires
Si vous voulez je peux vous montrer en visio quand vous voulez

**Comment by thibault** [comment]
@oceatoon Effectivement, le timing était précis :)

Pour info, je viens de procéder à la mise en production, vous pourrez donc accéder aux données de productions à cette adresse : 

https://aides-territoires.beta.gouv.fr/data/

Je serai très heureux d'avoir une idée dont la manière dont les données sont réutilisées.

**Comment by thibault** [comment]
Hello @oceatoon. Je viens aux nouvelles par pure curiosité. Avez-vous pu récupérer nos données de votre côté ? Est-ce qu'il y a un cas d'utilisation disponible quelque part ? Est-ce que tu as un retour d'expérience ?

**Comment by oceatoon** [comment]
salut 
désolé on est dans le rush le plus complet en ce moment 
mais je vais revenir vers toi tres bientot 
a tres vite j'espere

**Comment by thibault** [comment]
@oceatoon Merci pour la réponse, bon courage pour le rush :)

**Comment by oceatoon** [comment]
salut @thibault 
ca y'est ca se clame , je vais enfin pouvoir venir m'amuser un peu avec toi / vous 
ca te dit une petite visio que je vous montre le cas d'usage et vous pourrez me conseiller la meilleure facon de rpocéder ?
