### ISSUE TITLE
[Ansible] Fichier .bashrc manquant dans le répertoire home du user aides

### ISSUE THREAD

**Issue by xavier-sanna** [MTES-MCT/aides-territoires#161]
Lors du déploiement Ansible, une erreur survient au moment d'ajouter l'export de la variable de settings django dans `.bashrc` car le fichier n'existe pas dans le home du user `aides`

Voici le message d'erreur avec un peu de verbose:

`
fatal: [aides.local]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "attributes": null,
            "backrefs": false,
            "backup": false,
            "content": null,
            "create": false,
            "delimiter": null,
            "directory_mode": null,
            "firstmatch": false,
            "follow": false,
            "force": null,
            "group": null,
            "insertafter": "EOF",
            "insertbefore": null,
            "line": "export DJANGO_SETTINGS_MODULE=core.settings.local",
            "mode": null,
            "owner": null,
            "path": "/home/aides/.bashrc",
            "regexp": "'^export DJANGO_SETTINGS_MODULE",
            "remote_src": null,
            "selevel": null,
            "serole": null,
            "setype": null,
            "seuser": null,
            "src": null,
            "state": "present",
            "unsafe_writes": null,
            "validate": null
        }
    },`
    **"msg": "Destination /home/aides/.bashrc does not exist !",**
    `"rc": 257
}
`

Il faudrait s'assurer que le fichier `.bashrc` existe bien avant d’exécuter cette tache

**Comment by samuelpath** [comment]
@joe-mc-krusty J'ai rencontré le même souci lors du déploiement Ansible.

Je vais mettre à jour le `user.yml` pour qu'il vérifie si `/home/aides/.bashrc` existe bien, et si ce n'est pas le cas, de le créer en fichier vide.

**Comment by samuelpath** [comment]
@thibault Voici l'action que je propose de rajouter avant l'action `Make sure the django settings module env is set` qui tente d'écrire dans le `.bashrc` : 

```yml
- name: "Make sure {{ install_root }}/.bashrc file exists before writing into it"
  copy:
    content: ""
    dest: "{{ install_root }}/.bashrc"
    force: no
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: '0660'
```

Voici la doc sur le module copy : https://docs.ansible.com/ansible/latest/modules/copy_module.html.
Et voici une explication du choix de mes paramètres et de leurs valeurs : 

| Paramètre | Valeur | Explication |
| ---------- | ------- | ---------- |
|content|""|Si le fichier n'existe pas, on crée un fichier vide|
|dest|"{{ install_root }}/.bashrc"| Ce qui donne : /home/aides/.bashrc|
|force|no|Si le fichier existe déjà, on ne fait rien|
|owner|"{{ user_name }}"|Comme pour les autres actions|
|group|"{{ user_name }}"|Comme pour les autres actions|
|mode|'0660'|[Lecture/écriture juste pour le owner et le groupe](https://chmodcommand.com/chmod-660/)|
