### ISSUE TITLE
aria-label sur bouton navbar non lu par screen reader

### ISSUE THREAD

**Issue by samuelpath** [MTES-MCT/aides-territoires#189]
Je me connecte avec un compte de publieur d'aides.
J'utilise un screen reader (p.ex. ChromeVox sur Chrome).
Via la navigation par tab, je passe sur le bouton avec mon nom, qui est aussi un menu déroulant: 

![image](https://user-images.githubusercontent.com/6030745/94666527-e23c6880-030d-11eb-8791-19023e6e9fe7.png)

Le screen reader me lit:

```
Liste avec 1 élément: élément de liste
Samuel Path
Lien interne
```

À aucun moment l'attribut `aria-label="Afficher / masquer le menu"` du bouton semble n'être pris en compte.

En revanche, si je déplace cet attribut sur le le lien contenant mon nom, le `aria-label` est bien lu à la place de mon nom, et on a donc:

```
Liste avec 1 élément: élément de liste
Afficher / masquer le menu
Lien interne
```

Il faudrait éventuellement revoir les attributs ARIA de cette navigation, car une personne à déficience visuelle aurait du mal à faire sens de ce que le screen reader lit actuellement.

**Comment by Ash-Crow** [comment]
Cela semble bon sur la version actuelle.
