### ISSUE TITLE
pourquoi les variables sont-elles en anglais ?

### ISSUE THREAD

**Issue by sycom** [MTES-MCT/aides-territoires#79]
En explorant la documentation de l'API, on constate que tous les noms de variables sont en anglais.

Quelle est la plus-value de ce choix pour un programme français, sont toute la documentation est également en français?

**Comment by thibault** [comment]
Bonjour @sycom,

L'API est destinée à être consommée par des logiciels. L'anglais est la lange *de facto* de l'informatique, et toute la base de code est en anglais. Il y a donc une certaine cohérence à présenter les champs en anglais.

**Comment by sycom** [comment]
Mouais, je suis moyennement convaincu par l'argumentaire. Les développeurs qui vont utiliser l'API seront essentiellement francophones. Les logiciels ne sont pas encore assez autonomes pour développer du code tous seuls, il me semble. L'anglais (ou disons le globish) est _de facto_ la langue de l'informatique, mais il nous reste des marges de manœuvre...

Dans ce contexte très spécifique, il y aurait aussi une certaine cohérence à ce qu'un programme développé par une administration française pour des utilisateurs francophones, et a peu de chance de s'exporter, fasse d'autres choix. Pour une fois...

Je ne m'attendais pas à ce que vous réécriviez tout le code, mais ça mérite qu'on y pense (Je me vise moi-même à ma modeste échelle aussi). Je n'ai pas le sentiment d'avoir fait évoluer la pensée ici en tout cas. Merci d'avoir pris le temps de répondre en tout cas.

**Comment by thibault** [comment]
Re-bonjour @sycom,

Je t'assure que nos choix techniques sont pesés et mesurés.

La question de l'anglicisation des termes métiers fait débat depuis longtemps, chaque décision vient avec ses avantages et ses inconvénients.

L'avantage de l'anglais : la concision, une plus grande souplesse, moins d'ambiguïté, une plus grande cohérence de la base de code qui utilise massivement des frameworks et libs écrites en anglais. Du français : un moindre risque de confusion au niveau des traductions, une plus grande facilité d'accès pour les devs francophones et aussi, il faut bien avouer, une posture politique de lutte contre une certaine suprématie culturelle anglophone.

Tous les choix techniques ont un impact, nous n'avons pas la prétention de ne jamais commettre d'erreur ni de lire l'avenir, mais nous essayons de faire au mieux en gardant le maximum de cohérence et en ayant à l'esprit la pérénité du projet à long terme.

Je suis désolé si cette décision spécifiquement a choqué ta sensibilité ou t'a posé des difficultés techniques, ce n'était certes pas l'objectif.

**Comment by sycom** [comment]
@thibault Je ne suis pas choqué et n'ai pas rencontré de difficultés techniques. Je m'interroge comme tout le monde, ni plus ni moins. Et mes réponses ne sont pas meilleures que d'autres. D'ailleurs comme dit précédemment, j'ai fait des bouts de code qui utilisent des noms de variables en anglais - la force de l'habitude - pour des projets dont je sais que, dans le meilleur des cas, seuls des devs francophones les reprendront.

Et je suis à mon tour désolé, que ma réponse aie pu passer pour un jugement de valeur. En la relisant je comprends pourquoi. On veut faire court et on oublie des mots essentiels...

Bref, pas d'offense, pas de regrets délirants. Je continue à penser que quand on n'est pas sur un projet qui peut potentiellement avoir des visées internationales on doit pouvoir nommer ses variables et paramètres en _français_ (sans accents hein?), mais je comprends que d'autres fassent d'autres choix.
