### ISSUE TITLE
Le mini-site francetierslieux est difficile à lire en Dark Mode

### ISSUE THREAD

**Issue by thom4parisot** [MTES-MCT/aides-territoires#849]
Sur Firefox ça ressemble à ça : 

![image](https://user-images.githubusercontent.com/138627/147610294-beaed0bb-e1a5-4a48-8f16-ff6b896e1a3b.png)

**Comment by Ash-Crow** [comment]
Bonjour, cela devrait normalement être bon maintenant.

**Comment by thom4parisot** [comment]
Voici à quoi ça ressemble après avoir vidé le cache : 

![image](https://user-images.githubusercontent.com/138627/156610719-27652f2c-9435-4d30-af06-ea383fb4ea0e.png)

**Comment by Ash-Crow** [comment]
Pouvez-vous s'il vous plaît donner des précisions sur l'OS et navigateur utilisé ?

Comment est gérée la préférence pour le dark mode (thème navigateur, extension ?)

**Comment by thom4parisot** [comment]
Et bien… j'ai nettoyé mes cookies et le localStorage, puis j'ai forcé le dark mode au niveau du système. L'apparence a changé 🙃 

![image](https://user-images.githubusercontent.com/138627/156759276-f2b132b2-8918-4a2f-9869-39e86412ec54.png)

J'utilise Firefox 97.0.1 sur macOS.

La fois précédente, j'ai utilisé les devTools de Firefox pour basculer du thème clair au thème sombre.
